create table proyecto (
	nombre		varchar(50),
	caracter	varchar(20)	not null,
	duracion	varchar(15)	not null,
	CONSTRAINT	cp_PROYECTO PRIMARY KEY (nombre),
	CONSTRAINT	valor_erroneo_caracter	CHECK (caracter = 'GENERICO' or caracter = 'ESPECIFICO')
)
/
insert into PROYECTO values ('AGRICULTURA ECOBIO', 'GENERICO', '30 MESES');
insert into PROYECTO values ('AGRICULTURA TERCER MUNDO', 'ESPECIFICO', 'INDEFINIDO');
insert into PROYECTO values ('AGRICULTURA TRANSGENICA', 'GENERICO', '15 MESES');
insert into PROYECTO values ('PISCICULTURA ECOBIO', 'GENERICO', '36 MESES');
insert into PROYECTO values ('PISCICULTURA TERCER MUNDO', 'ESPECIFICO', '100 SEMANAS');
insert into PROYECTO values ('PISCICULTURA TRANSGENICA', 'GENERICO', '36 MESES');
insert into PROYECTO values ('GANADERIA ECOBIO', 'GENERICO', '42 MESES');
insert into PROYECTO values ('GANADERIA TERCER MUNDO', 'GENERICO', '200 SEMANAS');
insert into PROYECTO values ('GANADERIA TRANSGENICA', 'ESPECIFICO', '25 MESES');
insert into PROYECTO values ('REGADIO ECOBIO', 'GENERICO', '40 MESES');
insert into PROYECTO values ('SECANO ECOBIO', 'GENERICO', '50 MESES');
insert into PROYECTO values ('TECNOLOGIA APLICADA AL MUNDO NATURAL', 'GENERICO', '60 MESES');
insert into PROYECTO values ('TECNOLOGIA APLICADA EN EL TERCER MUNDO', 'ESPECIFICO', '70 MESES');
insert into PROYECTO values ('TECNOLOGIA APLICADA AL MEDIO RURAL', 'ESPECIFICO', '30 MESES');
insert into PROYECTO values ('TECNOLOGIA APLICADA EN PAISES EN DESARROLLO', 'GENERICO', '30 MESES');
insert into PROYECTO values ('INFORMATICA EN ENTORNOS RURALES', 'GENERICO', '300 SEMANAS');
insert into PROYECTO values ('INFORMATICA EN PAISES EN DESARROLLO', 'ESPECIFICO', '80 MESES');
insert into PROYECTO values ('INFORMATICA EN EL TERCER MUNDO', 'GENERICO', '90 MESES');
insert into PROYECTO values ('INTELIGENCIA ARTIFICIAL APLICADA EN AGRICULTURA', 'ESPECIFICO', '400 SEMANAS');
insert into PROYECTO values ('INTELIGENCIA ARTIFICIAL EN ENTORNOS RURALES', 'ESPECIFICO', '100 MESES');