create table emp_tra_pro (
	dni_emp	char(9),
	nombre	varchar(50),
	CONSTRAINT	cp_EMP_TRA_PRO	PRIMARY KEY(dni_emp, nombre),
	CONSTRAINT	ca_dni_emp__EMP_TRA_PRO FOREIGN KEY (dni_emp) REFERENCES emple (dni),
	CONSTRAINT	ca_nombre__EMP_TRA_PRO FOREIGN KEY (nombre) REFERENCES proyecto (nombre)
)
/
insert into EMP_TRA_PRO values ('10101010A', 'AGRICULTURA ECOBIO');
insert into EMP_TRA_PRO values ('20202020B', 'AGRICULTURA TERCER MUNDO');
insert into EMP_TRA_PRO values ('30303030C', 'AGRICULTURA TRANSGENICA');
insert into EMP_TRA_PRO values ('40404040D', 'PISCICULTURA ECOBIO');
insert into EMP_TRA_PRO values ('50505050E', 'PISCICULTURA TERCER MUNDO');
insert into EMP_TRA_PRO values ('60606060F', 'PISCICULTURA TRANSGENICA');
insert into EMP_TRA_PRO values ('70707070G', 'GANADERIA ECOBIO');
insert into EMP_TRA_PRO values ('10101010A', 'INTELIGENCIA ARTIFICIAL EN ENTORNOS RURALES');
insert into EMP_TRA_PRO values ('20202020B', 'INTELIGENCIA ARTIFICIAL EN ENTORNOS RURALES');
insert into EMP_TRA_PRO values ('30303030C', 'INTELIGENCIA ARTIFICIAL EN ENTORNOS RURALES');
insert into EMP_TRA_PRO values ('40404040D', 'INTELIGENCIA ARTIFICIAL EN ENTORNOS RURALES');
insert into EMP_TRA_PRO values ('50505050E', 'INTELIGENCIA ARTIFICIAL APLICADA EN AGRICULTURA');
insert into EMP_TRA_PRO values ('60606060F', 'INTELIGENCIA ARTIFICIAL APLICADA EN AGRICULTURA');
insert into EMP_TRA_PRO values ('70707070G', 'INTELIGENCIA ARTIFICIAL APLICADA EN AGRICULTURA');
insert into EMP_TRA_PRO values ('80808080H', 'GANADERIA TERCER MUNDO');
insert into EMP_TRA_PRO values ('90909090I', 'GANADERIA TRANSGENICA');
insert into EMP_TRA_PRO values ('10101010A', 'AGRICULTURA TERCER MUNDO');
insert into EMP_TRA_PRO values ('20202020B', 'AGRICULTURA ECOBIO');
insert into EMP_TRA_PRO values ('30303030C', 'AGRICULTURA ECOBIO');
insert into EMP_TRA_PRO values ('40404040D', 'AGRICULTURA ECOBIO');
insert into EMP_TRA_PRO values ('50505050E', 'AGRICULTURA ECOBIO');
insert into EMP_TRA_PRO values ('60606060F', 'AGRICULTURA ECOBIO');
insert into EMP_TRA_PRO values ('70707070G', 'AGRICULTURA TERCER MUNDO');
insert into EMP_TRA_PRO values ('80808080H', 'AGRICULTURA TERCER MUNDO');
insert into EMP_TRA_PRO values ('90909090I', 'AGRICULTURA TERCER MUNDO');
insert into EMP_TRA_PRO values ('10101010A', 'REGADIO ECOBIO');
insert into EMP_TRA_PRO values ('20202020B', 'REGADIO ECOBIO');
insert into EMP_TRA_PRO values ('30303030C', 'REGADIO ECOBIO');
insert into EMP_TRA_PRO values ('40404040D', 'SECANO ECOBIO');
insert into EMP_TRA_PRO values ('50505050E', 'SECANO ECOBIO');
insert into EMP_TRA_PRO values ('60606060F', 'SECANO ECOBIO');
insert into EMP_TRA_PRO values ('70707070G', 'TECNOLOGIA APLICADA AL MUNDO NATURAL');
insert into EMP_TRA_PRO values ('80808080H', 'TECNOLOGIA APLICADA AL MUNDO NATURAL');
insert into EMP_TRA_PRO values ('90909090I', 'TECNOLOGIA APLICADA AL MUNDO NATURAL');
insert into EMP_TRA_PRO values ('11111111J', 'REGADIO ECOBIO');
insert into EMP_TRA_PRO values ('12121212K', 'SECANO ECOBIO');
insert into EMP_TRA_PRO values ('13131313L', 'TECNOLOGIA APLICADA AL MUNDO NATURAL');
insert into EMP_TRA_PRO values ('14141414M', 'TECNOLOGIA APLICADA EN EL TERCER MUNDO');
insert into EMP_TRA_PRO values ('15151515N', 'TECNOLOGIA APLICADA AL MEDIO RURAL');
insert into EMP_TRA_PRO values ('16161616O', 'TECNOLOGIA APLICADA EN PAISES EN DESARROLLO');
insert into EMP_TRA_PRO values ('17171717P', 'INFORMATICA EN ENTORNOS RURALES');
insert into EMP_TRA_PRO values ('18181818Q', 'INFORMATICA EN PAISES EN DESARROLLO');
insert into EMP_TRA_PRO values ('19191919R', 'INFORMATICA EN EL TERCER MUNDO');
insert into EMP_TRA_PRO values ('11111111J', 'INTELIGENCIA ARTIFICIAL APLICADA EN AGRICULTURA');
insert into EMP_TRA_PRO values ('12121212K', 'INTELIGENCIA ARTIFICIAL APLICADA EN AGRICULTURA');
insert into EMP_TRA_PRO values ('13131313L', 'INTELIGENCIA ARTIFICIAL APLICADA EN AGRICULTURA');
insert into EMP_TRA_PRO values ('14141414M', 'INTELIGENCIA ARTIFICIAL EN ENTORNOS RURALES');
insert into EMP_TRA_PRO values ('15151515N', 'INTELIGENCIA ARTIFICIAL EN ENTORNOS RURALES');
insert into EMP_TRA_PRO values ('16161616O', 'INTELIGENCIA ARTIFICIAL EN ENTORNOS RURALES');
insert into EMP_TRA_PRO values ('17171717P', 'INTELIGENCIA ARTIFICIAL EN ENTORNOS RURALES');
insert into EMP_TRA_PRO values ('18181818Q', 'INTELIGENCIA ARTIFICIAL EN ENTORNOS RURALES');
insert into EMP_TRA_PRO values ('19191919R', 'INTELIGENCIA ARTIFICIAL EN ENTORNOS RURALES');
insert into EMP_TRA_PRO values ('21212121S', 'INTELIGENCIA ARTIFICIAL APLICADA EN AGRICULTURA');
insert into EMP_TRA_PRO values ('22222222T', 'INTELIGENCIA ARTIFICIAL EN ENTORNOS RURALES');
insert into EMP_TRA_PRO values ('23232323U', 'INTELIGENCIA ARTIFICIAL EN ENTORNOS RURALES');
insert into EMP_TRA_PRO values ('24242424V', 'INTELIGENCIA ARTIFICIAL EN ENTORNOS RURALES');
insert into EMP_TRA_PRO values ('25252525W', 'INTELIGENCIA ARTIFICIAL APLICADA EN AGRICULTURA');
insert into EMP_TRA_PRO values ('26262626X', 'INTELIGENCIA ARTIFICIAL APLICADA EN AGRICULTURA');
insert into EMP_TRA_PRO values ('27272727Y', 'INTELIGENCIA ARTIFICIAL APLICADA EN AGRICULTURA');
insert into EMP_TRA_PRO values ('28282828Z', 'INTELIGENCIA ARTIFICIAL APLICADA EN AGRICULTURA');
insert into EMP_TRA_PRO values ('29292929A', 'INFORMATICA EN EL TERCER MUNDO');
insert into EMP_TRA_PRO values ('31313131B', 'INFORMATICA EN EL TERCER MUNDO');
insert into EMP_TRA_PRO values ('32323232C', 'INFORMATICA EN EL TERCER MUNDO');